[build-system]
requires = ["setuptools>=65.5.3"]
build-backend = "setuptools.build_meta"

[project]
name = "scena"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = ["torch", "roma", "viser", "tyro", "ninja"]

[project.optional-dependencies]
dev = ["ruff", "ipdb", "pytest", "line_profiler", "pre-commit"]

[tool.setuptools.packages.find]
include = ["scena"]
